// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItauTopFive.Migrations
{
    [DbContext(typeof(ItauTopFiveDbContext))]
    [Migration("20260301140710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_basket_item");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Percentage")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("vl_percentage");

                    b.Property<int>("RecommendationBasketId")
                        .HasColumnType("int")
                        .HasColumnName("id_basket");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_symbol");

                    b.Property<int>("id_basket")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_basket");

                    b.ToTable("tb_basket_items", null, t =>
                        {
                            t.Property("id_basket")
                                .HasColumnName("id_basket1");
                        });
                });

            modelBuilder.Entity("Custody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_custody");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_average_price");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("vl_quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_symbol");

                    b.Property<int>("TradingAccountId")
                        .HasColumnType("int")
                        .HasColumnName("id_trading_account");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TradingAccountId");

                    b.ToTable("tb_custodies", (string)null);
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("st_cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("st_email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("fl_active");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_monthly_contribution");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("st_name");

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_subscription_date");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_cpf");

                    b.ToTable("tb_customers", (string)null);
                });

            modelBuilder.Entity("Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_distribution");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildAccountId")
                        .HasColumnType("int")
                        .HasColumnName("id_child_account");

                    b.Property<DateTime>("DistributedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExecutionPrice")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_execution_price");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("id_purchase_order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("vl_quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tb_distributions", (string)null);
                });

            modelBuilder.Entity("PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_purchase_order");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_execution_date");

                    b.Property<int>("MarketType")
                        .HasColumnType("int")
                        .HasColumnName("tp_market_type");

                    b.Property<int>("MasterAccountId")
                        .HasColumnType("int")
                        .HasColumnName("id_master_account");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("vl_quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_symbol");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_unit_price");

                    b.HasKey("Id");

                    b.ToTable("tb_purchase_orders", (string)null);
                });

            modelBuilder.Entity("Rebalancing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rebalancing");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyTicker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_buy_ticker");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("vl_quantity");

                    b.Property<DateTime>("RebalancingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_rebalancing");

                    b.Property<string>("SellTicker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_sell_ticker");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("tp_rebalancing_type");

                    b.HasKey("Id");

                    b.ToTable("tb_rebalancings", (string)null);
                });

            modelBuilder.Entity("RecommendationBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_basket");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("fl_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("st_name");

                    b.HasKey("Id");

                    b.ToTable("tb_recommendation_baskets", (string)null);
                });

            modelBuilder.Entity("TaxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tax_event");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_base_amount");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_event_date");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_tax_amount");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("tp_tax_type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("tb_tax_events", (string)null);
                });

            modelBuilder.Entity("Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ticker");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_created_at");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("vl_current_price");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("st_symbol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_updated_at");

                    b.HasKey("Id");

                    b.ToTable("tb_tickers", (string)null);
                });

            modelBuilder.Entity("TradingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trading_account");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<int>("CustomerId1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("st_description");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("tp_account_type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("CustomerId1");

                    b.ToTable("tb_trading_accounts", (string)null);
                });

            modelBuilder.Entity("BasketItem", b =>
                {
                    b.HasOne("RecommendationBasket", null)
                        .WithMany("Items")
                        .HasForeignKey("id_basket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Custody", b =>
                {
                    b.HasOne("Customer", null)
                        .WithMany("Custodies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingAccount", null)
                        .WithMany("Custodies")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxEvent", b =>
                {
                    b.HasOne("Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TradingAccount", b =>
                {
                    b.HasOne("Customer", null)
                        .WithOne("TradingAccount")
                        .HasForeignKey("TradingAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Navigation("Custodies");

                    b.Navigation("TradingAccount")
                        .IsRequired();
                });

            modelBuilder.Entity("RecommendationBasket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TradingAccount", b =>
                {
                    b.Navigation("Custodies");
                });
#pragma warning restore 612, 618
        }
    }
}
